spring.cloud.stream:
  bindings:
    t1:
      destination: t1
      consumer:
        headerMode: raw
    t2:
      destination: t2
      consumer:
        headerMode: raw
    t3:
      destination: t3
      consumer:
        headerMode: raw
  kafka.streams:
    binder:
      brokers: localhost
      zk-nodes: localhost
      configuration.commit.interval.ms: 1000
    bindings:
      t1.consumer.application-id: t1t2appid
      t2.consumer.application-id: t1t2appid
      t3.consumer.application-id: t3appid